'use strict'

module.exports = (sequelize, DataTypes) => {  
  const Players = sequelize.define('players', {
    // Sysem
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4,
      allowNull: false
    },
    team_id: {
      type: DataTypes.UUID,
      allowNull: false
    },
    // user generated
    description: {
      type: DataTypes.TEXT,
      required: true
    },
    status: DataTypes.BOOLEAN,
    // autogenerated
    player: DataTypes.INTEGER, 
    // system
    created_at: {
      type: DataTypes.DATE,
      allowNull: false
    },
    updated_at:  DataTypes.DATE
  }, {
    underscored: true
  });

  return Players;
};